#!/bin/sh
#yorkie 2.0.0

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

# OS X and Linux only
load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR="$1"
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }
}

# OS X and Linux only
run_nvm () {
  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && [ -f .nvmrc ] && nvm use
}

cd "."

# Add common path where Node can be found
# Brew standard installation path /usr/local/bin
# Node standard installation path /usr/local
# Poetry standard installation path ~/.local/bin
export PATH="$PATH:/usr/local/bin:/usr/local:~/.local/bin"

# Try to load nvm using path of standard installation
load_nvm /Users/johnnyxcy/.nvm
run_nvm

# Export Git hook params
export GIT_PARAMS="$*"

# Run hook
poetry run python "tools/toolbox/scripts/git_hooks.py" pre-commit || {
  echo
  echo "pre-commit hook failed (add --no-verify to bypass)"
  exit 1
}
